trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'springboot-app'
  ACR_NAME: 'myacr0065'
  RESOURCE_GROUP: 'myResourceGroup'
  CLUSTER_NAME: 'myAKSCluster'
  NAMESPACE: 'default'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Set Java 17'

  - script: java -version
    displayName: 'Check Java Version'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      publishJUnitResults: false

  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      command: 'buildAndPush'
      repository: '$(IMAGE_NAME)'
      dockerfile: 'Dockerfile'
      containerRegistry: 'my-acr-connection'
      tags: 'latest'

  - task: KubernetesManifest@1
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'my-k8s-connection'
      namespace: '$(NAMESPACE)'
      manifests: 'deployment.yaml'
    displayName: 'Deploy to AKS'
