# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'springboot-app'
  ACR_NAME: 'myacr0065'
  RESOURCE_GROUP: 'myResourceGroup'
  CLUSTER_NAME: 'myAKSCluster'
  NAMESPACE: 'default'

steps:
  # ✅ Add Java 17 Setup
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '17'
      jdkArchitecture: 'x64'
    displayName: 'Set up Java 17'

  # ✅ Run Maven Build
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      publishJUnitResults: false
    displayName: 'Maven Build'

  # ✅ Build and Push Docker Image
  - script: |
      docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest .
      az acr login --name $(ACR_NAME)
      docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
    displayName: 'Build and Push Docker Image'

  # ✅ Deploy to AKS
  - task: KubernetesManifest@1
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'my-k8s-connection'
      namespace: '$(NAMESPACE)'
      manifests: 'deployment.yaml'
    displayName: 'Deploy to AKS'
